/* eslint-disable max-len */
export const WORKSPACES_IS_FETCHING_SEATINFOS = `WORKSPACES_IS_FETCHING_SEATINFOS`
export const WORKSPACES_FETCH_SEATINFOS_SUCCESS = `WORKSPACES_FETCH_SEATINFOS_SUCCESS`
export const WORKSPACES_FETCH_SEATINFOS_FAILURE = `WORKSPACES_FETCH_SEATINFOS_FAILURE`
export const WORKSPACES_IS_FETCHING_HISTORIC_DATA = `WORKSPACES_IS_FETCHING_HISTORIC_DATA`
export const WORKSPACES_FETCH_HISTORIC_DATA_SUCCESS = `WORKSPACES_FETCH_HISTORIC_DATA_SUCCESS `
export const WORKSPACES_FETCH_HISTORIC_DATA_FAILURE = `WORKSPACES_FETCH_HISTORIC_DATA_FAILURE `
export const WORKSPACES_TOGGLE_FAVOURITE = `WORKSPACES_TOGGLE_FAVOURITE`
export const WORKSPACES_SET_SEARCH_QUERY = `WORKSPACES_SET_SEARCH_QUERY`
export const WORKSPACES_SET_SORT_TYPE = `WORKSPACES_SET_SORT_TYPE`
export const WORKSPACES_SORT_TYPES = {
  NAME: `name`,
  VACANCIES: `vacancies`,
}
export const WORKSPACES_IS_FETCHING_DETAILS = `WORKSPACES_IS_FETCHING_DETAILS`
export const WORKSPACES_FETCH_DETAILS_SUCCESS = `WORKSPACES_FETCH_DETAILS_SUCCESS`
export const WORKSPACES_FETCH_DETAILS_FAILURE = `WORKSPACES_FETCH_DETAILS_FAILURE`
