// this file was generated by the populateSurveyList.js script
module.exports = {
  surveys: [
    {
      id: 22,
      name: "UCL Wolfson Study",
      active: true,
      start_time: "09:00",
      end_time: "17:00",
      maps: [
        {
          id: 84,
          name: "Wolfson Study",
          image_id: 93,
        },
      ],
    },
    {
      id: 58,
      name: "UCL Student Centre",
      active: true,
      start_time: "09:00",
      end_time: "17:00",
      maps: [
        {
          id: 128,
          name: "Student Centre Ground Floor",
          image_id: 139,
        },
        {
          id: 129,
          name: "Student Centre Mezzanine",
          image_id: 140,
        },
        {
          id: 133,
          name: "Student Centre 1st Floor",
          image_id: 144,
        },
        {
          id: 130,
          name: "Student Centre 2nd Floor",
          image_id: 141,
        },
        {
          id: 134,
          name: "Student Centre 3rd Floor",
          image_id: 145,
        },
        {
          id: 131,
          name: "Student Centre 4th Floor",
          image_id: 142,
        },
        {
          id: 135,
          name: "Student Centre Level B1",
          image_id: 146,
        },
        {
          id: 132,
          name: "Student Centre Level B2",
          image_id: 143,
        },
      ],
    },
    {
      id: 39,
      name: "UCL SSEES Library",
      active: true,
      start_time: "00:00",
      end_time: "24:00",
      maps: [
        {
          id: 99,
          name: "Basement",
          image_id: 108,
        },
        {
          id: 100,
          name: "Ground",
          image_id: 109,
        },
        {
          id: 101,
          name: "First",
          image_id: 110,
        },
        {
          id: 102,
          name: "Second",
          image_id: 111,
        },
      ],
    },
    {
      id: 33,
      name: "UCL SENIT Suite",
      active: true,
      start_time: "09:00",
      end_time: "17:00",
      maps: [
        {
          id: 91,
          name: "Senit Suite",
          image_id: 100,
        },
      ],
    },
    {
      id: 35,
      name: "UCL Senate House Hub",
      active: true,
      start_time: "09:00",
      end_time: "17:00",
      maps: [
        {
          id: 86,
          name: "Senate House",
          image_id: 95,
        },
      ],
    },
    {
      id: 19,
      name: "UCL Science Library",
      active: true,
      start_time: "09:00",
      end_time: "17:00",
      maps: [
        {
          id: 108,
          name: "Ground",
          image_id: 117,
        },
        {
          id: 109,
          name: "Ground Mez",
          image_id: 118,
        },
        {
          id: 110,
          name: "1st Floor",
          image_id: 119,
        },
        {
          id: 111,
          name: "2nd Floor",
          image_id: 120,
        },
        {
          id: 112,
          name: "3rd Floor",
          image_id: 121,
        },
        {
          id: 113,
          name: "4th Floor",
          image_id: 122,
        },
      ],
    },
    {
      id: 27,
      name: "UCL School of Pharmacy Library",
      active: true,
      start_time: "08:40",
      end_time: "22:00",
      maps: [
        {
          id: 83,
          name: "SoP Library",
          image_id: 92,
        },
      ],
    },
    {
      id: 38,
      name: "UCL Main Library",
      active: true,
      start_time: "09:00",
      end_time: "17:00",
      maps: [
        {
          id: 103,
          name: "1st West",
          image_id: 112,
        },
        {
          id: 104,
          name: "1st East",
          image_id: 113,
        },
        {
          id: 105,
          name: "Law",
          image_id: 114,
        },
        {
          id: 106,
          name: "2nd West",
          image_id: 115,
        },
        {
          id: 107,
          name: "2nd East",
          image_id: 116,
        },
      ],
    },
    {
      id: 14,
      name: "UCL Language & Speech Science Library",
      active: true,
      start_time: "09:00",
      end_time: "20:00",
      maps: [
        {
          id: 96,
          name: "L&SS",
          image_id: 105,
        },
      ],
    },
    {
      id: 47,
      name: "UCL Institute of Orthopaedics Library",
      active: true,
      start_time: "08:30",
      end_time: "20:00",
      maps: [
        {
          id: 90,
          name: "Orthopaedics",
          image_id: 99,
        },
      ],
    },
    {
      id: 28,
      name: "UCL Institute of Neurology, Queen Square Library",
      active: true,
      start_time: "09:00",
      end_time: "19:00",
      maps: [
        {
          id: 89,
          name: "Neurology",
          image_id: 98,
        },
      ],
    },
    {
      id: 46,
      name: "UCL Institute of Education Library",
      active: true,
      start_time: "08:30",
      end_time: "23:30",
      maps: [
        {
          id: 114,
          name: "Level 4",
          image_id: 123,
        },
        {
          id: 115,
          name: "Level 3",
          image_id: 126,
        },
        {
          id: 116,
          name: "Level 5",
          image_id: 127,
        },
      ],
    },
    {
      id: 7,
      name: "UCL Institute of Archaeology Library",
      active: true,
      start_time: "09:30",
      end_time: "21:00",
      maps: [
        {
          id: 87,
          name: "Archeaology",
          image_id: 96,
        },
      ],
    },
    {
      id: 12,
      name: "UCL Great Ormond Street Institute of Child Health Library",
      active: true,
      start_time: "09:00",
      end_time: "18:00",
      maps: [
        {
          id: 88,
          name: "ICH",
          image_id: 97,
        },
      ],
    },
    {
      id: 9,
      name: "UCL Eastman Dental Library",
      active: true,
      start_time: "09:00",
      end_time: "20:00",
      maps: [
        {
          id: 98,
          name: "EDI",
          image_id: 107,
        },
      ],
    },
    {
      id: 16,
      name: "UCL Ear Institute & Hearing Loss Library",
      active: true,
      start_time: "09:00",
      end_time: "19:00",
      maps: [
        {
          id: 119,
          name: "Ear 1st Floor",
          image_id: 130,
        },
        {
          id: 120,
          name: "Ear Mez",
          image_id: 131,
        },
      ],
    },
    {
      id: 45,
      name: "UCL Cruciform Hub",
      active: true,
      start_time: "09:00",
      end_time: "17:00",
      maps: [
        {
          id: 117,
          name: "Main Area",
          image_id: 128,
        },
        {
          id: 118,
          name: "Clusters",
          image_id: 129,
        },
      ],
    },
    {
      id: 8,
      name: "UCL Bartlett Library",
      active: true,
      start_time: "09:00",
      end_time: "20:00",
      maps: [
        {
          id: 97,
          name: "Bartlett",
          image_id: 106,
        },
      ],
    },
    {
      id: 6,
      name: "UCL Anatomy Hub ",
      active: true,
      start_time: "09:00",
      end_time: "17:00",
      maps: [
        {
          id: 95,
          name: "Anatomy Hub",
          image_id: 104,
        },
      ],
    },
    {
      id: 40,
      name: "The Joint Library of Ophthalmology",
      active: true,
      start_time: "08:00",
      end_time: "21:00",
      maps: [
        {
          id: 94,
          name: "Opthalmology",
          image_id: 103,
        },
      ],
    },
    {
      id: 32,
      name: "Royal Free Hospital Medical Library",
      active: true,
      start_time: "09:00",
      end_time: "17:00",
      maps: [
        {
          id: 121,
          name: "Royal Free New Layout",
          image_id: 132,
        },
        {
          id: 93,
          name: "Royal Free Old",
          image_id: 102,
        },
      ],
    },
    {
      id: 11,
      name: "Graduate Hub",
      active: true,
      start_time: "09:00",
      end_time: "17:00",
      maps: [
        {
          id: 85,
          name: "South Wing",
          image_id: 94,
        },
      ],
    },
    {
      id: 10,
      name: "Foster Court",
      active: true,
      start_time: "08:00",
      end_time: "20:00",
      maps: [
        {
          id: 92,
          name: "Foster Court",
          image_id: 101,
        },
      ],
    },
    {
      id: 49,
      name: "1 Saint Martin Le Grand - Ended 06/03/19",
      active: true,
      start_time: "09:00",
      end_time: "17:00",
      maps: [
        {
          id: 82,
          name: "1SMLG",
          image_id: 91,
        },
      ],
    },
    {
      id: 59,
      name: "1 Saint Martin Le Grand",
      active: true,
      start_time: "09:00",
      end_time: "17:00",
      maps: [
        {
          id: 138,
          name: "1SMLG",
          image_id: 149,
        },
      ],
    },
  ],
};
