export const WORKSPACES_IS_FETCHING_SEATINFOS =
  "WORKSPACES_IS_FETCHING_SEATINFOS";
export const WORKSPACES_FETCH_SEATINFOS_SUCCESS =
  "WORKSPACES_FETCH_SEATINFOS_SUCCESS";
export const WORKSPACES_FETCH_SEATINFOS_FAILURE =
  "WORKSPACES_FETCH_SEATINFOS_FAILURE";
export const WORKSPACES_IS_FETCHING_HISTORIC_DATA =
  "WORKSPACES_IS_FETCHING_HISTORIC_DATA";
export const WORKSPACES_FETCH_HISTORIC_DATA_SUCCESS =
  "WORKSPACES_FETCH_HISTORIC_DATA_SUCCESS ";
export const WORKSPACES_FETCH_HISTORIC_DATA_FAILURE =
  "WORKSPACES_FETCH_HISTORIC_DATA_FAILURE ";
export const STUDYSPACE_TOGGLE_FAVOURITE = "STUDYSPACE_TOGGLE_FAVOURITE";
