export const IS_SIGNING_IN = `IS_SIGNING_IN`
export const SIGN_IN_SUCCESS = `SIGN_IN_SUCCESS`
export const SIGN_IN_FAILURE = `SIGN_IN_FAILURE`
export const SIGN_IN_CANCEL = `SIGN_IN_CANCEL`
export const SIGN_OUT_USER = `SIGN_OUT_USER`
export const DECLINE_PUSH_NOTIFICATIONS = `DECLINE_PUSH_NOTIFICATIONS`
export const SET_EXPO_PUSH_TOKEN = `SET_EXPO_PUSH_TOKEN`
export const SET_SHOULD_TRACK_ANALYTICS = `SET_SHOULD_TRACK_ANALYTICS`
