version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/London"
    allow:
      - dependency-type: "all"
    reviewers:
      - "hueyy"
    ignore:
      - dependency-name: "babel-core"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-native*"
      - dependency-name: "lottie-react-native"
      - dependency-name: "react-native-svg"
      - dependency-name: "@react-native-community/*"
      - dependency-name: "expo-*"
