version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
    ignored_updates:
      - match:
          dependency_name: "babel-core"
      - match:
          dependency_name: "react"
      - match:
          dependency_name: "react-dom"
      - match:
          dependency_name: "react-test-renderer"
      - match:
          dependency_name: "react-native*"
      - match:
          dependency_name: "lottie-react-native"
      - match:
          dependency_name: "react-native-svg"
      - match:
          dependency_name: "@react-native-community/datetimepicker"
      - match:
          dependency_name: "@react-native-community/viewpager"
