name: build & test
on:
  push:
    paths-ignore:
      - ".github/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Expo GitHub Action
      uses: expo/expo-github-action@v5
      with:
        expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
        expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
        expo-cache: true
    - run: echo '${{ secrets.APP_JSON }}' > app.json
    - run: npm ci

    - name: codechecks
      run: npx codechecks
      env:
        CC_SECRET: ${{ secrets.CC_SECRET }}

    - run: npm run test

    - run: expo doctor

    - name: deploy
      if: github.ref != 'refs/heads/master'
      run: |
          expo publish --release-channel=dev.commit-${{ github.sha }}
    - uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
      with:
        msg: Published to [dev.commit-${{ github.sha }}](https://expo.io/@${{ secrets.EXPO_CLI_USERNAME }}/ucl-assistant?release-channel=dev.commit-${{ github.sha }}).

